
name: 'getaction'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '* * * * *' # 定义 cron 表达式
  watch:
    types: [started] # 定义star是自动发送

  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: 'Install dependencies1'
      run: python -m pip install --upgrade pip
    - name: 'Install dependencies2'
      run: pip install -r requirements.txt
    - name: '开始运行shengcehngcsv22.py'
      env:
        SCKEY: ${{ secrets.SCKEY }}
      run: python shengcehngcsv22.py
    - name: commit2
      run: |
        git config --global user.email 1438457833@qq.com
        git config --global user.name marsggbo211
        git add .
        git commit -m "update" -a
    - name: Push changes2
      uses: ad-m/github-push-action@master
  
